# Generated by Django 4.2.5 on 2023-09-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profileuser_working_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='working_at',
            field=models.CharField(blank=True, default='#', max_length=150, null=True),
        ),
    ]
