# Generated by Django 4.2.4 on 2023-09-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_postmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-post_date',)},
        ),
    ]
