# Generated by Django 4.2.4 on 2023-09-15 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_userfollowing_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='like_owner',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='liked_post',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='like_owner',
            field=models.ManyToManyField(related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='liked_post',
            field=models.ManyToManyField(related_name='liked_post', to='core.postmodel'),
        ),
    ]
