# Generated by Django 4.2.4 on 2023-09-15 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_remove_likemodel_like_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='like_owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='liked_post',
            field=models.ManyToManyField(to='core.postmodel'),
        ),
    ]
