# Generated by Django 4.2.4 on 2023-09-15 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_alter_likemodel_like_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='like_owner',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='liked_post',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='like_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='liked_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='core.postmodel'),
        ),
    ]
