# Generated by Django 4.2.4 on 2023-09-15 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_alter_likemodel_like_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', through='core.LikeModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
